/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Plugin {
  msg: string
}
export interface Config {
  plugin: Plugin
}
export function run(config: Config): void
