[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
napi = "2.9.0"
napi-derive = "2.9.0"
plugin = {path="../plugin"}

[lib]
crate-type = ["cdylib"]
